### ISSUE TITLE
Add sticky footer to skeleton template

### ISSUE THREAD

**Issue by quillcraftsman** [quillcraftsman/lavacactus#12]
In the template footer go to top. For example on contact page: https://lavacactus.craftsman.lol/contact.html

In this example on bootstrap 5: https://getbootstrap.com/docs/5.0/examples/sticky-footer/ - works fine. 

I've tried to use `fixed-bottom` but it's a bad way. Footer will ride on text then browser become smaller.

**Comment by hind-sagar-biswas** [comment]
Roger that

**Comment by hind-sagar-biswas** [comment]
BTW, do I still need to work-code-push to make contributions?

**Comment by hind-sagar-biswas** [comment]
Pull request sent, #16

**Comment by quillcraftsman** [comment]
Pull request has been merged. @hind-sagar-biswas , https://lavacactus.craftsman.lol/ - now footer looks great. And all new projects with this template will be beautiful

**Comment by hind-sagar-biswas** [comment]
@quillcraftsman BTW, do I still need to work-code-push to make contributions?

**Comment by quillcraftsman** [comment]
> @quillcraftsman BTW, do I still need to work-code-push to make contributions?

@hind-sagar-biswas , Yes I think so. That is the other option?

**Comment by hind-sagar-biswas** [comment]
> > @quillcraftsman BTW, do I still need to work-code-push to make contributions?
> 
> @hind-sagar-biswas , Yes I think so. That is the other option?

Oh I see, thanks for informing, but to fork everytime to do anything is kinda chore

**Comment by quillcraftsman** [comment]
> > > @quillcraftsman BTW, do I still need to work-code-push to make contributions?
> > 
> > 
> > @hind-sagar-biswas , Yes I think so. That is the other option?
> 
> Oh I see, thanks for informing, but to fork everytime to do anything is kinda chore

@hind-sagar-biswas , I think I understand what is about. You shouldn't fork every time, you can make fork once. Then at the top of repository near the "Contribute button" there is another button ("Sync Fork"). If you see that original repository was changed you can use this button to pull changes to your forked repository.
